global:
  scrape_interval: 15s # Intervalo de tiempo entre la captura de métricas

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']  # Exportador de Docker
